name = "SH44E"
author = "vPanzerbrigade 21 S4"
prefix = "sh44e"
mainprefix = "z"

[files]
include = [
    "mod.cpp",
    "READDME.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_sh44e_ca.paa"
]

[asc]
enabled = true
exclude = [
    "/xeh_prep.sqf",
]

[version]
git_hash = 0 # Disabled